#ifndef UTL_CONCATENATE_HPP
#define UTL_CONCATENATE_HPP

#define UTL_CONCATENATE_WITHOUT_EXPANSION(x, y) \
    x ## y

#define UTL_CONCATENATE(x, y) \
    UTL_CONCATENATE_WITHOUT_EXPANSION(x, y)

#endif // UTL_CONCATENATE_HPP
